// <auto-generated />
using System;
using CarbonNow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarbonNow.Migrations
{
    [DbContext(typeof(CarbonNowDbContext))]
    [Migration("20250616233928_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarbonNow.Model.ElectricalItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsumoKwh")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtUso")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmissaoCalculada")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("NomeItem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioId");

                    b.ToTable("ElectricalItems");
                });

            modelBuilder.Entity("CarbonNow.Model.Transport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ConformeIso")
                        .HasColumnType("bit");

                    b.Property<int>("DistanciaKm")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtUso")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmissaoCalculada")
                        .HasColumnType("int");

                    b.Property<int>("EmissaoPermitidaIso")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("TipoTransporte")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioId");

                    b.ToTable("Transports");
                });

            modelBuilder.Entity("CarbonNow.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarbonNow.Model.ElectricalItem", b =>
                {
                    b.HasOne("CarbonNow.Model.User", "IdUsuario")
                        .WithMany()
                        .HasForeignKey("IdUsuarioId");

                    b.Navigation("IdUsuario");
                });

            modelBuilder.Entity("CarbonNow.Model.Transport", b =>
                {
                    b.HasOne("CarbonNow.Model.User", "IdUsuario")
                        .WithMany()
                        .HasForeignKey("IdUsuarioId");

                    b.Navigation("IdUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
